### ISSUE TITLE
عدم وجود توابع بنر استاندارد

### ISSUE THREAD

**Issue by AlirezaDadrass** [tapsellorg/TapsellPlusSDK-FlutterSample#1]
سلام.
من پروژه تست رو ببرسی کردم و بخش مربوط به بنر استاندارد هیچ کدی نداره. و تابع خالی هست!
برای استفاده از این امکان چیکار باید کرد؟
ممنونم

**Comment by behdad222** [comment]
سلام
بنر استاندارد هنوز تو فلاتر قابل استفاده نیست

**Comment by AlirezaDadrass** [comment]
ممنونم.
راه حلی وجود داره که بتونم از بنر استاندارد استفاده کنم؟

**Comment by behdad222** [comment]
چرا از native banner استفاده نمیکنید؟

**Comment by AlirezaDadrass** [comment]
با طراحی اپلیکیشنم سازگار نیست.

**Comment by behdad222** [comment]
بنر نیتیو برای این هست که هر جور دوست دارید دیزاین رو تغییر بدید تا مطابق با دیزاین اپلیکیشن خودتون بشه

**Comment by AlirezaDadrass** [comment]
بسیار عالی. الان کد رو دقیق تر خوندم متوجه سبکش شدم. فکر میکردم حتما باید چیدمان موزاییکی داشته باشم. 
خیلی از پاسخ گویی سریعتون ممنونم
