### ISSUE TITLE
هیچ پیاده سازی برای بنر استاندارد تو فلاتر ندارید

### ISSUE THREAD

**Issue by sadrash** [tapsellorg/TapsellPlusSDK-FlutterSample#2]

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود

پلاگین بازنویسی شده و در حال حاضر بنر استاندارد اضافه شده. اما پلن برای بهبودش (که بشه مستقیما بهش بعنوان ویجت نگاه کرد و نه اندروید ویوو) هست.

[ریلیز نهایی](https://pub.dev/packages/tapsell_plus)

</div>

**Comment by sadrash** [comment]
با سلام
پیام شما دریافت شد با تشکر
