### ISSUE TITLE
Error when using showBannerAd to get standard banner ad

### ISSUE THREAD

**Issue by DanialV** [tapsellorg/TapsellPlusSDK-FlutterSample#3]
Get this error on using banner ad

Failed to handle method call
E/MethodChannel#tapsell_plus(18900): kotlin.KotlinNullPointerException
E/MethodChannel#tapsell_plus(18900): 	at ir.tapsell.tapsell_plus.TapsellPlusPlugin.onMethodCall(TapsellPlusPlugin.kt:137)
E/MethodChannel#tapsell_plus(18900): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#tapsell_plus(18900): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#tapsell_plus(18900): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#tapsell_plus(18900): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#tapsell_plus(18900): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#tapsell_plus(18900): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#tapsell_plus(18900): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#tapsell_plus(18900): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#tapsell_plus(18900): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#tapsell_plus(18900): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by mahdi-malv** [comment]
Plugin is re-written. Checkout the [latest release](https://pub.dev/packages/tapsell_plus).

I'll close the issue. Feel free to re-open if you still got the issue with the latest (2.1.3 at the time) version
