### ISSUE TITLE
TapsellPlusSDK-FlutterSample/lib/StandardBannerPage.dart

### ISSUE THREAD

**Issue by sky93** [tapsellorg/TapsellPlusSDK-FlutterSample#4]
https://github.com/tapsellorg/TapsellPlusSDK-FlutterSample/blob/9ac5c8f0bf641eef0ad308c4e4c2121502f66567/lib/StandardBannerPage.dart#L28

این تابع خالی هست!!

**Comment by mahdi-malv** [comment]
Releated [#5](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/issues/5)

<div dir='rtl'>

در حال حاضر پلاگین کار میکنه (مجدد نوشته شده) در صورتی که مشکلی مجدد وجود داشت حتما اطلاع بدید تا اقدام به حلش کنم.
با تشکر

</div>
