### ISSUE TITLE
Flutter Null Safety

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [tapsellorg/TapsellPlusSDK-FlutterSample#5]
Hello
Any plans to migrate your package to null-safety?
since I'm using this package in some of my projects so when I want to migrate them to null-safety I have the following error:
null-safety compatible versions do not exist for:
 - tapsell_plus

please provide it ASAP. 
Thanks

**Comment by mahdi-malv** [comment]
Hello,
sorry for late response since the last update on plugin

Tapsell-plus now supports null-safety ([Latest release in pub](https://pub.dev/packages/tapsell_plus))
