### ISSUE TITLE
Missing `key.properties` file to test example in release mode

### ISSUE THREAD

**Issue by javaherisaber** [tapsellorg/TapsellPlusSDK-FlutterSample#6]
There is a sign.jks file in `example/android/app` directory but there is no equivalent `key.properties` file

**Comment by mahdi-malv** [comment]
Oh thanks. Will add a fix for that.

Until then, use a dummy one if needed:

```groovy
keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
```
